version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    command: yarn start

  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
